#
# ps10pr2.py - Problem Set 10, Problem 2
#
# Markov text generation
#

import random

# 1.

def create_dictionary(filename):
    """ returns a dictionary of key-value pairs in which:
            each key is a word encountered in the text file;
            the corresponding value is a list of words that
            follow the key word in the text file.
    """
    file = open(filename, 'r')
    text = file.read()
    file.close()
    words = text.split()
    
    d = {}
    current_word = '$'
    
    for next_word in words:

        if current_word[-1] in '.!?':
            current_word = '$'
        if current_word not in d:
            d[current_word] = [next_word]
            current_word = next_word
        else:
            d[current_word] += [next_word]
            current_word = next_word
    return d

# 2.

def generate_text(word_dict, num_words):
    """ takes as parameters a dictionary of word transitions
        (generated by the create_dictionary function) named word_dict
        and a positive integer named num_words.
        The function should use word_dict to generate and print num_words words.
    """
    current_word = '$'

    for count in range(num_words):

        if current_word[-1] in '.!?':
            current_word = '$'
            wordlist = word_dict[current_word]
            next_word = random.choice(wordlist)
            print(next_word, end=' ')
            current_word = next_word
        else:
            wordlist = word_dict[current_word]
            next_word = random.choice(wordlist)
            print(next_word, end=' ')
            current_word = next_word
    print()
